import Foundation

public enum TrackAvailability: String, Codable, Sendable, Equatable { case available, unavailable, unknown }
public struct ProviderTrackState: Codable, Sendable, Equatable { public let provider: MusicProvider; public let trackID: String; public let availability: TrackAvailability; public let offlineReady: Bool; public init(provider: MusicProvider, trackID: String, availability: TrackAvailability, offlineReady: Bool) { self.provider=provider; self.trackID=trackID; self.availability=availability; self.offlineReady=offlineReady } }
public struct TrackReadiness: Codable, Sendable, Equatable { public let plannedTrack: MusicTrack; public let selectedTrack: MusicTrack?; public let usedFallback: Bool; public let readyForOffline: Bool; public let reason: String? }
public struct MusicReadinessReport: Codable, Sendable, Equatable { public let provider: MusicProvider; public let tracks:[TrackReadiness]; public var isPlayable:Bool { tracks.allSatisfy{$0.selectedTrack != nil} }; public var isOfflineReady:Bool { isPlayable && tracks.allSatisfy{$0.readyForOffline} }; public var fallbackCount:Int { tracks.filter(\.usedFallback).count } }
public struct MusicFallbackEngine: Sendable {
    public init() {}
    public func assess(plan: PlaylistPlan, provider: MusicProvider, states:[String:ProviderTrackState], fallbackCatalog:[MusicTrack]) -> MusicReadinessReport {
        var usedIDs=Set<String>(); var results:[TrackReadiness]=[]
        for entry in plan.entries { let original=entry.track; let originalProviderID=original.providerIDs[provider]; let state=originalProviderID.flatMap{states[$0]}; if originalProviderID != nil, let state, state.availability == .available { usedIDs.insert(original.id); results.append(TrackReadiness(plannedTrack:original, selectedTrack:original, usedFallback:false, readyForOffline:state.offlineReady, reason:state.offlineReady ? nil : "Available but not downloaded for offline playback")); continue }; let replacement=bestFallback(for:original, provider:provider, states:states, catalog:fallbackCatalog, excluding:usedIDs); if let replacement { usedIDs.insert(replacement.id); let providerID=replacement.providerIDs[provider]!; let replacementState=states[providerID]!; results.append(TrackReadiness(plannedTrack:original, selectedTrack:replacement, usedFallback:true, readyForOffline:replacementState.offlineReady, reason:"Planned track unavailable; substituted closest eligible fallback")) } else { results.append(TrackReadiness(plannedTrack:original, selectedTrack:nil, usedFallback:false, readyForOffline:false, reason:"No playable provider match or fallback available")) } }
        return MusicReadinessReport(provider:provider, tracks:results)
    }
    private func bestFallback(for target:MusicTrack, provider:MusicProvider, states:[String:ProviderTrackState], catalog:[MusicTrack], excluding usedIDs:Set<String>) -> MusicTrack? { catalog.filter { track in guard !usedIDs.contains(track.id), let pid=track.providerIDs[provider], let state=states[pid] else { return false }; return state.availability == .available }.max { score($0,target:target) < score($1,target:target) } }
    private func score(_ candidate:MusicTrack, target:MusicTrack) -> Double { var score=0.0; score += candidate.preferenceScore*4; score += candidate.familiarity*2; if candidate.artist.caseInsensitiveCompare(target.artist) == .orderedSame { score += 1.5 }; if let a=candidate.bpm, let b=target.bpm { score += max(0,2-abs(a-b)/8) }; if let a=candidate.energy, let b=target.energy { score += max(0,1.5-abs(a-b)*3) }; score += max(0,1-abs(candidate.durationSeconds-target.durationSeconds)/90); return score }
}
