import Foundation

public enum PlaylistOptimizerError: Error, Equatable { case noCandidates }

public struct HeuristicPlaylistOptimizer: PlaylistOptimizing {
    private struct State { var used:Set<String>; var entries:[PlaylistEntry]; var elapsed:TimeInterval; var qualitySum:Double }
    public init() {}
    public func optimize(request:RunRequest, runner:RunnerProfile, preference:MusicPreference, candidates:[MusicTrack]) throws -> PlaylistPlan {
        let filtered = candidates.filter { preference.explicitContentAllowed || !$0.explicit }
        guard !filtered.isEmpty else { throw PlaylistOptimizerError.noCandidates }
        let targetDuration=request.targetDurationSeconds; let targetCadence=request.desiredCadenceSPM ?? runner.typicalCadenceSPM; let milestoneTimes=markerTargetTimes(request:request); let maxDuration=targetDuration+240; let beamWidth=240; let maxTracks=min(filtered.count,Int(ceil(targetDuration/150))+5)
        var beam=[State(used:[],entries:[],elapsed:0,qualitySum:0)]; var finals:[State]=[]
        for _ in 0..<maxTracks { var next:[State]=[]; next.reserveCapacity(beam.count * min(filtered.count,12)); for state in beam { if state.elapsed >= targetDuration-75 { finals.append(state) }; if state.elapsed > maxDuration { continue }; let progress=min(max(state.elapsed/targetDuration,0),1); let targetEnergy=energyTarget(for:request,progress:progress); for track in filtered where !state.used.contains(track.id) { let scored=trackScore(track,targetCadence:targetCadence,targetEnergy:targetEnergy,recentEntries:state.entries); let distanceAtStart=min(request.distanceMeters,state.elapsed/request.targetPaceSecondsPerKilometer*1000); let entry=PlaylistEntry(track:track,startsAtSeconds:state.elapsed,expectedDistanceMeters:distanceAtStart,score:scored.score,reasons:scored.reasons); var used=state.used; used.insert(track.id); next.append(State(used:used,entries:state.entries+[entry],elapsed:state.elapsed+track.durationSeconds,qualitySum:state.qualitySum+scored.score)) } }; if next.isEmpty { break }; next.sort { stateObjective($0,targetDuration:targetDuration,milestoneTimes:milestoneTimes,partial:true) > stateObjective($1,targetDuration:targetDuration,milestoneTimes:milestoneTimes,partial:true) }; beam=Array(next.prefix(beamWidth)) }
        finals.append(contentsOf:beam)
        guard let best=finals.max(by:{ stateObjective($0,targetDuration:targetDuration,milestoneTimes:milestoneTimes,partial:false) < stateObjective($1,targetDuration:targetDuration,milestoneTimes:milestoneTimes,partial:false) }) else { throw PlaylistOptimizerError.noCandidates }
        let markers=buildMarkers(entries:best.entries,request:request)
        return PlaylistPlan(requestedDurationSeconds:targetDuration,plannedDurationSeconds:best.elapsed,entries:best.entries,markers:markers,objectiveScore:stateObjective(best,targetDuration:targetDuration,milestoneTimes:milestoneTimes,partial:false))
    }
    private func trackScore(_ track:MusicTrack,targetCadence:Double?,targetEnergy:Double,recentEntries:[PlaylistEntry])->(score:Double,reasons:[String]) { let preferenceScore=0.42*track.preferenceScore+0.18*track.familiarity; let energyScore:Double = track.energy.map{0.2*(1-min(abs($0-targetEnergy),1))} ?? 0.1; let cadenceScore:Double; var reasons=[String](); if let cadence=targetCadence, let bpm=track.bpm { let error=min(abs(bpm-cadence),abs((bpm*2)-cadence),abs((bpm/2)-cadence)); cadenceScore=0.16*max(0,1-error/18); if error<=6 { reasons.append("tempo fits cadence") } } else { cadenceScore=0.08 }; let artistPenalty=recentEntries.suffix(3).contains{$0.track.artist.caseInsensitiveCompare(track.artist)==.orderedSame} ? 0.15:0; let score=preferenceScore+energyScore+cadenceScore-artistPenalty; if track.preferenceScore>=0.8 { reasons.append("strong music preference") }; if abs((track.energy ?? targetEnergy)-targetEnergy)<=0.12 { reasons.append("energy fits this segment") }; return(score,reasons) }
    private func stateObjective(_ state:State,targetDuration:TimeInterval,milestoneTimes:[TimeInterval],partial:Bool)->Double { guard !state.entries.isEmpty else{return -100}; let qualityMean=state.qualitySum/Double(state.entries.count); let durationError=abs(state.elapsed-targetDuration); let startTimes=state.entries.map(\.startsAtSeconds); let reachable=partial ? milestoneTimes.filter{$0<=state.elapsed+180}:milestoneTimes; let timingError=reachable.reduce(0.0){sum,milestone in sum + min(startTimes.map{abs($0-milestone)}.min() ?? 300,300)}/max(Double(reachable.count),1); let durationPenalty=partial ? max(0,state.elapsed-targetDuration)/900:durationError/900; return qualityMean-durationPenalty-timingError/240 }
    private func markerTargetTimes(request:RunRequest)->[TimeInterval] { let count=Int(floor(request.distanceMeters/request.milestoneDistanceMeters)); guard count>0 else{return[]}; return (1...count).map{ let distance=min(Double($0)*request.milestoneDistanceMeters,request.distanceMeters); return distance/1000*request.targetPaceSecondsPerKilometer } }
    private func energyTarget(for request:RunRequest,progress:Double)->Double { if !request.musicEnergyAnchors.isEmpty { let distance=progress*request.distanceMeters; let anchors=request.musicEnergyAnchors; if distance<=anchors[0].distanceMeters{return anchors[0].targetEnergy}; if distance>=anchors[anchors.count-1].distanceMeters{return anchors[anchors.count-1].targetEnergy}; for pair in zip(anchors,anchors.dropFirst()) { if distance>=pair.0.distanceMeters && distance<=pair.1.distanceMeters { let width=max(pair.1.distanceMeters-pair.0.distanceMeters,1); let t=(distance-pair.0.distanceMeters)/width; return pair.0.targetEnergy+(pair.1.targetEnergy-pair.0.targetEnergy)*t } } }; switch request.energyProfile { case .steady:return 0.68; case .progressive:return 0.52+0.38*progress; case .negativeSplit:return progress<0.5 ? 0.58:0.68+0.25*((progress-0.5)/0.5); case .conservativeStartStrongFinish: if progress<0.25{return 0.48}; if progress<0.75{return 0.66}; return 0.82+0.12*((progress-0.75)/0.25) } }
    private func buildMarkers(entries:[PlaylistEntry],request:RunRequest)->[MileMarker] { guard !entries.isEmpty else{return[]}; let count=Int(floor(request.distanceMeters/request.milestoneDistanceMeters)); guard count>0 else{return[]}; return (1...count).map{ index in let targetDistance=min(Double(index)*request.milestoneDistanceMeters,request.distanceMeters); let targetTime=targetDistance/1000*request.targetPaceSecondsPerKilometer; let nearest=entries.min{abs($0.startsAtSeconds-targetTime)<abs($1.startsAtSeconds-targetTime)}!; return MileMarker(milestoneNumber:index,targetDistanceMeters:targetDistance,targetTimeSeconds:targetTime,nearestTrackID:nearest.track.id,timingErrorSeconds:nearest.startsAtSeconds-targetTime) } }
}
