import Foundation

public enum ReadinessSeverity: String, Codable, Sendable, Equatable, Comparable { case ready, warning, blocking; public static func < (lhs:ReadinessSeverity,rhs:ReadinessSeverity)->Bool{ let rank:[ReadinessSeverity:Int]=[.ready:0,.warning:1,.blocking:2]; return rank[lhs,default:0] < rank[rhs,default:0] } }
public struct ReadinessCheck: Codable, Sendable, Equatable, Identifiable { public let id:String; public let title:String; public let severity:ReadinessSeverity; public let detail:String; public let recoveryAction:String?; public init(id:String,title:String,severity:ReadinessSeverity,detail:String,recoveryAction:String?=nil){self.id=id;self.title=title;self.severity=severity;self.detail=detail;self.recoveryAction=recoveryAction} }
public struct PreRunContext: Sendable { public let runnerProfile:RunnerProfile; public let playlistPlan:PlaylistPlan; public let musicReadiness:MusicReadinessReport; public let course:RaceCourse?; public let pendingEventCount:Int; public let availableLocalStorageBytes:Int64?; public let watchBatteryPercent:Double?; public init(runnerProfile:RunnerProfile,playlistPlan:PlaylistPlan,musicReadiness:MusicReadinessReport,course:RaceCourse?=nil,pendingEventCount:Int=0,availableLocalStorageBytes:Int64?=nil,watchBatteryPercent:Double?=nil){self.runnerProfile=runnerProfile;self.playlistPlan=playlistPlan;self.musicReadiness=musicReadiness;self.course=course;self.pendingEventCount=max(0,pendingEventCount);self.availableLocalStorageBytes=availableLocalStorageBytes;self.watchBatteryPercent=watchBatteryPercent} }
public struct PreRunReadinessReport: Sendable, Equatable { public let checks:[ReadinessCheck]; public var overall:ReadinessSeverity{checks.map(\.severity).max() ?? .ready}; public var canStart:Bool{overall != .blocking} }
public struct PreRunReadinessEngine: Sendable {
    public init(){}
    public func assess(_ context:PreRunContext)->PreRunReadinessReport { var checks:[ReadinessCheck]=[]; checks.append(ReadinessCheck(id:"runner-data",title:"Runner profile",severity:context.runnerProfile.dataConfidence >= 0.35 ? .ready:.warning,detail:context.runnerProfile.dataConfidence >= 0.35 ? "Enough data is available to personalize this run." : "Personalization confidence is limited; manual metrics or more run history will improve it.")); checks.append(ReadinessCheck(id:"music-playable",title:"Music availability",severity:context.musicReadiness.isPlayable ? .ready:.blocking,detail:context.musicReadiness.isPlayable ? "Every planned slot has a playable track or fallback." : "At least one playlist slot has no playable track.",recoveryAction:context.musicReadiness.isPlayable ? nil : "Regenerate missing tracks before starting.")); checks.append(ReadinessCheck(id:"music-offline",title:"Offline music",severity:context.musicReadiness.isOfflineReady ? .ready:.warning,detail:context.musicReadiness.isOfflineReady ? "The music plan is ready for offline playback." : "Music is playable, but one or more tracks are not confirmed for offline playback.",recoveryAction:context.musicReadiness.isOfflineReady ? nil : "Download the generated playlist in the music provider before race day.")); if let course=context.course { let verified=course.sourceURL != nil || course.verifiedEdition != nil; checks.append(ReadinessCheck(id:"course",title:"Race course",severity:verified ? .ready:.warning,detail:verified ? "Course source or edition is recorded." : "Course is unverified; race-day music timing may use the wrong course profile.",recoveryAction:verified ? nil : "Verify the official course or import a GPX/FIT/TCX file.")) }; if context.pendingEventCount > 500 { checks.append(ReadinessCheck(id:"sync-backlog",title:"Sync backlog",severity:.warning,detail:"A large telemetry backlog is waiting to sync.",recoveryAction:"Open the app online before the run so prior data can finish syncing.")) }; if let bytes=context.availableLocalStorageBytes, bytes < 50*1024*1024 { checks.append(ReadinessCheck(id:"storage",title:"Local storage",severity:.blocking,detail:"Not enough local storage is available for a reliable offline session.",recoveryAction:"Free at least 50 MB before starting.")) }; if let battery=context.watchBatteryPercent { let severity:ReadinessSeverity = battery < 0.15 ? .blocking : (battery < 0.30 ? .warning : .ready); checks.append(ReadinessCheck(id:"watch-battery",title:"Watch battery",severity:severity,detail:"Watch battery is \(Int(battery * 100))%.",recoveryAction:severity == .ready ? nil : "Charge the Watch before a long run or race.")) }; return PreRunReadinessReport(checks:checks) }
}
