import Foundation

public enum SyncState:String,Codable,Sendable,CaseIterable{case localOnly,queued,syncing,synced,failed}
public struct OfflineEvent:Codable,Sendable,Equatable,Identifiable{public let id:UUID;public let recordedAt:Date;public let kind:String;public let payload:Data;public var syncState:SyncState;public var attemptCount:Int;public var lastAttemptAt:Date?;public var lastError:String?;public init(id:UUID=UUID(),recordedAt:Date=Date(),kind:String,payload:Data,syncState:SyncState=.localOnly,attemptCount:Int=0,lastAttemptAt:Date?=nil,lastError:String?=nil){self.id=id;self.recordedAt=recordedAt;self.kind=kind;self.payload=payload;self.syncState=syncState;self.attemptCount=max(0,attemptCount);self.lastAttemptAt=lastAttemptAt;self.lastError=lastError}}
public protocol OfflineEventStoring:Sendable{func append(_ event:OfflineEvent) async throws;func all() async throws->[OfflineEvent];func pending(limit:Int) async throws->[OfflineEvent];func update(_ event:OfflineEvent) async throws}
public actor InMemoryOfflineEventStore:OfflineEventStoring{private var events:[OfflineEvent]=[];public init(){};public func append(_ event:OfflineEvent){events.append(event)};public func all()->[OfflineEvent]{events};public func pending(limit:Int=100)->[OfflineEvent]{Array(events.filter{$0.syncState != .synced}.prefix(max(1,limit)))};public func update(_ event:OfflineEvent){guard let idx=events.firstIndex(where:{$0.id==event.id}) else{return};events[idx]=event};public func mark(_ id:UUID,state:SyncState){guard let idx=events.firstIndex(where:{$0.id==id}) else{return};events[idx].syncState=state}}
public actor FileOfflineEventStore:OfflineEventStoring{private let fileURL:URL;private var events:[OfflineEvent];public init(fileURL:URL)throws{self.fileURL=fileURL;let manager=FileManager.default;try manager.createDirectory(at:fileURL.deletingLastPathComponent(),withIntermediateDirectories:true);if manager.fileExists(atPath:fileURL.path){let data=try Data(contentsOf:fileURL);self.events=data.isEmpty ? []:try JSONDecoder.runMusic.decode([OfflineEvent].self,from:data)}else{self.events=[]}};public func append(_ event:OfflineEvent)throws{events.append(event);try persist()};public func all()->[OfflineEvent]{events};public func pending(limit:Int=100)->[OfflineEvent]{Array(events.filter{$0.syncState != .synced}.prefix(max(1,limit)))};public func update(_ event:OfflineEvent)throws{guard let idx=events.firstIndex(where:{$0.id==event.id}) else{return};events[idx]=event;try persist()};private func persist()throws{let data=try JSONEncoder.runMusic.encode(events);try data.write(to:fileURL,options:[.atomic])}}
public protocol EventSyncTransport:Sendable{func upload(_ event:OfflineEvent) async throws}
public struct SyncRunResult:Sendable,Equatable{public let attempted:Int;public let synced:Int;public let failed:Int;public init(attempted:Int,synced:Int,failed:Int){self.attempted=attempted;self.synced=synced;self.failed=failed}}
public actor OfflineSyncCoordinator{private let store:any OfflineEventStoring;private let transport:any EventSyncTransport;private let maxAttempts:Int;public init(store:any OfflineEventStoring,transport:any EventSyncTransport,maxAttempts:Int=8){self.store=store;self.transport=transport;self.maxAttempts=max(1,maxAttempts)};public func syncPending(limit:Int=100,now:Date=Date()) async->SyncRunResult{let pending:[OfflineEvent];do{pending=try await store.pending(limit:limit)}catch{return SyncRunResult(attempted:0,synced:0,failed:0)};var synced=0;var failed=0;var attempted=0;for original in pending where original.attemptCount<maxAttempts{attempted+=1;var event=original;event.syncState = .syncing;event.attemptCount += 1;event.lastAttemptAt=now;event.lastError=nil;try? await store.update(event);do{try await transport.upload(event);event.syncState = .synced;event.lastError=nil;try? await store.update(event);synced+=1}catch{event.syncState = .failed;event.lastError=String(describing:error);try? await store.update(event);failed+=1}};return SyncRunResult(attempted:attempted,synced:synced,failed:failed)}}
public enum RunEventKind:String,Codable,Sendable{case workoutStarted,sample,milestoneReached,playbackChanged,workoutPaused,workoutResumed,workoutEnded}
public struct RunTelemetrySample:Codable,Sendable,Equatable{public let elapsedSeconds:TimeInterval;public let distanceMeters:Double;public let heartRateBPM:Double?;public let cadenceSPM:Double?;public let powerWatts:Double?;public let paceSecondsPerKilometer:Double?;public init(elapsedSeconds:TimeInterval,distanceMeters:Double,heartRateBPM:Double?=nil,cadenceSPM:Double?=nil,powerWatts:Double?=nil,paceSecondsPerKilometer:Double?=nil){self.elapsedSeconds=max(0,elapsedSeconds);self.distanceMeters=max(0,distanceMeters);self.heartRateBPM=heartRateBPM;self.cadenceSPM=cadenceSPM;self.powerWatts=powerWatts;self.paceSecondsPerKilometer=paceSecondsPerKilometer}}
extension JSONEncoder{fileprivate static var runMusic:JSONEncoder{let encoder=JSONEncoder();encoder.dateEncodingStrategy = .iso8601;encoder.outputFormatting=[.sortedKeys];return encoder}}
extension JSONDecoder{fileprivate static var runMusic:JSONDecoder{let decoder=JSONDecoder();decoder.dateDecodingStrategy = .iso8601;return decoder}}
